.TH Simple_Shell "August 2023" "Simple Shell" "man Page-user manual"
.SH NAME
Simple Shell
.SH SYNOPSIS
.B #!/bin/sh
.SH COMPILE
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 *.c -o hsh
.SH DESCRIPTION
In this home made version, Simple Shell is a command-line interpreter or
a command-line interface that behaves like a Unix Shell.
.SH RETURN
depending on the user input
.SH BUGS
none at the moment
.SH AUTHORS
Miguel Figuroa, Carlos Carrasquillo and Nadja Miranda



